### ISSUE TITLE
Is there any way to have CTkInputDialog use 'show=*' for a password

### ISSUE THREAD

**Issue by Cromwell1963** [TomSchimansky/CustomTkinter#1038]
I am setting up a simple password GUI and wondered if there Is any way to have CTkInputDialog use 'show=*' for a password.
thanks

**Comment by iTerminatorX** [comment]
use the argument (show='*') when you instantiate the entry widget. example:

entry = customtkinter.CTkEntry(master=root_tk, placeholder_text="CTkEntry", show='*')

**Comment by Cromwell1963** [comment]
Thank you for replying, but i don't have access to the entry widget as I am using the CTkInputDialog.

**Comment by Cromwell1963** [comment]
Yes, in the end i created my own dialog and used the show=* as you suggested, thanks

**Comment by Acidical** [comment]
ran into this same issue, and as a quick and simple hack you can do this right after instantiating the CTkInputDialog class:
```
dialog.after(20, lambda: dialog._entry.configure(show="*"))
```
this simply waits for the widgets on the dialog to be created, then modifies the show value of the entry to whatever you wish

be aware however this is just a workaround i am using until the ability to pass the show option to CTkInputDialog is added to this library

oh and while i was checking the CTkInputDialog code for this issue, i noticed that both the okay button and cancel button are bound to the okay buttons event, with the cancel event never being used, meaning the dialog input is returned even when cancel is pressed, this should probably be fixed

and using the same stupid workaround i altered that too for the meantime because why not:
```
dialog.after(20, lambda: dialog._cancel_button.configure(command=dialog._cancel_event))
```

 i will open a pull request to fix the event bug and add the ability to properly modify the show value of the entry if i have the time later

**Comment by Cromwell1963** [comment]
Thank you, that is really helpful.
