### ISSUE TITLE
CTk Button not working

### ISSUE THREAD

**Issue by DarthBoson** [TomSchimansky/CustomTkinter#1103]
When I run my program, the buttons somehow activate themselves and give the output but then after clicking them it wont show anything or give the output. Here is the code where the issue occurs

[code.txt](https://github.com/TomSchimansky/CustomTkinter/files/10482918/code.txt)

**Comment by duruburak** [comment]
I noticed the `command` argument was wrongly used. You should drop the parentheses, so the format should be like this:
`command = self.file_button_event`.

If you need to pass a value to the function, use `lambda`:
`command = lambda: self.file_button_event(0)`.

And it would be more convenient if you just paste your code into your post instead of uploading the file.

**Comment by DarthBoson** [comment]
Yeah after removing the parentheses, the buttons worked. Thanks for your help @duruburak .Also noted your code pasting advice.
