### ISSUE TITLE
Large text on Gnome breaks theme

### ISSUE THREAD

**Issue by chripede** [TomSchimansky/CustomTkinter#1130]
I run Gnome with 4K monitors, and the fix for HiDPI is scaling the font size (Large text in Accessibility). However that seems to break the layout.

It goes from looking like this:
![image](https://user-images.githubusercontent.com/406836/215323999-8ce65729-abfa-4f58-8407-963792911e50.png)

To this:
![image](https://user-images.githubusercontent.com/406836/215324036-e4a3a3e0-3f27-4ef1-9797-a8b56c473bda.png)

**Comment by TomSchimansky** [comment]
So GNOME has no 4K scaling and you are using the Accessibility setting to get some sort of scaling on the 4K monitor?
Think the problem is that the CustomTkimter widgets are also drawn with font shapes and it seems thy increase in size as well, I don't think I can do anything about this. If you want to scale only the Customtkinter window you can do:
```python
customtkinter.set_widget_scaling(2.0)
customtkinter.set_window_scaling(2.0)
```
