### ISSUE TITLE
Label's disabled state

### ISSUE THREAD

**Issue by RobbieKhan** [TomSchimansky/CustomTkinter#1151]
Hi everyone
In my application I use custom image buttons based on `CTkLabel`. Sometimes I need to change their state to `customtkinter.DISABLED/NORMAL`. It works normally except the background color in `DISABLED` state - as you see it fills label with some kind of small white grid that looks especially horrible with a Dark theme. Is there any way to remove it? I tried to find at least anything related to that in the sources of customtkinter and tkinter but couldn't even find where it is set.

Disabled state - annoying white 'grid':
![image](https://user-images.githubusercontent.com/53120051/215896383-4919f0ed-e12c-4f4e-ac17-5b733b5f14d8.png)
Normal state, everything is fine:
![image](https://user-images.githubusercontent.com/53120051/215896427-ebd99e7f-0d79-4342-b2ac-e803179a852f.png)

I will be very grateful for any hint/advice.
It is definitely not the problem of the image, I can remove image from that label and just set some text and this white 'grid' will still be there

**Comment by m-smid** [comment]
Hello,
I have kind of an workaround that I used before.....

Instead of using `state` you can have 2 images one representing the `state = normal` and 1 representing `state = disabled` and variable ( `StringVar` or `IntVar` -` self.format_var = tkinter.IntVar(value=0)` ) that will represent current state of your button.
With that you can create function that will `configure` functionality of your button, for example:
```
def configure_button(self, state):
    if state == 1:
        self.img_label.configure(image=self.image_for_normal_state)
        self.img_button.configure(command=self.intended_function)
    elif state == 0:
        self.img_label.configure(image=self.image_for_disabled_state)
        self.img_button.configure(command=None)
```
Action that decided if your button should be active or not will set value of `self.format_var` and call this function.

Button will technically be always active, but will appear like disabled and will have no action assigned to it while 'disabled'.

**Comment by RobbieKhan** [comment]
@m-smid, hi, thank you for your response! Yes, I did exactly the same in the past :) This time just wanted to make everything using as much standart methods as it possible. Thought, maybe someone knows the reason of that.
