### ISSUE TITLE
Make components compatible with background images.

### ISSUE THREAD

**Issue by vednig** [TomSchimansky/CustomTkinter#12]
Enhancement:

- Make components compatible with background images.

Currently:

- 
![image](https://user-images.githubusercontent.com/64083352/140304308-c893a3e1-c60e-4913-a25f-6039ff29584e.png)

**Comment by TomSchimansky** [comment]
That would be great but sadly that's not possible with Tkinter, or to be more precise, its not possible in the way how I draw the buttons. Because I draw the buttons on a Canvas which is rectangular and I simply set the bg color of the canvas to the color that's behind it. Because in Tkinter its not possible to make the background of the Canvas transparent as far as I now.
So a possibility would be that you pass the bg image to the button and I crop the exact part out of the image that the button covers and place it on the canvas of the button, but that would be difficult to get exactly right and you wouldn't be able to move the button.
So as a workaround I would just do something like this:

<img width="1012" alt="Bildschirmfoto 2021-11-04 um 13 00 19" src="https://user-images.githubusercontent.com/66446067/140310713-1d66b7ee-beaa-4862-b995-ca825ff35579.png">

**Comment by vednig** [comment]
I'll try implementing soon. 
( Only for Static Images ) via bbox of component along with adding configure attribute to other components.

**Comment by Akascape** [comment]
@vednig A new solution for this issue: https://github.com/TomSchimansky/CustomTkinter/discussions/2214
