### ISSUE TITLE
drop down of option menu and Combo box is not rounded

### ISSUE THREAD

**Issue by SiveshJ** [TomSchimansky/CustomTkinter#1221]
![Screenshot 2023-02-12 154454](https://user-images.githubusercontent.com/125117014/218305239-b2dad8ed-61cf-470a-a2e9-a455be18b86a.jpg)
The drop down is not rounded like the image on documentation. Both Combo box and Option menu are like that. This is the code I used to create the widget. I am using windows
`meaning_entry = customtkinter.CTkComboBox(frame_meaning,width=400,height=30,font=('Century gothic',22),dropdown_font=('Century gothic',22),corner_radius=10,command=search_meaning)

ctk_optionmenu = customtkinter.CTkOptionMenu(frame_meaning,values=['option1','option2','option3'],font=('Century gothic',22),dropdown_font=('Century gothic',22))`   

Is something wrong with my code

**Comment by Wolf-SO** [comment]
> This is the code I used to create the widget.

Please post the *minimal* example code that can be run by everyone to reproduce your issue. And *please* fix the [markup for the code](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks). Here is one way to make code boxes work:

    ```python
    import customtkinter

    # more lines
    ```
 Thanks!

**Comment by Akascape** [comment]
Combobox and Optionmenu uses the classic **tkinter menu** widget to display the values.

**Comment by TomSchimansky** [comment]
The menu was implemented with a toplevel window and rounded edges first, but then I used the standard tkinter menus because of multiple platform dependant bugs I couldn't solve.

**Comment by Akascape** [comment]
Hello @TomSchimansky, I feel like the dropdown menu should be replaced by the old toplevel.
Problem with Tkinter Menu:
- No ability to adjust width and height properly
- No ability to scroll through options
- Covers the whole screen height if we provide too many options
- Sharp corners and borders
 
If we use the toplevel menu again, we can do some fixes. 
- Apply rounded corners for only mac/windows because it has the transparency attributes. But for other os like linux, it is a limitation so they will have to stay with sharp corners. At least it will look better than the tk menu.

```python
if sys.platform.startswith("win"):
        self.transparent_color = '#000001'
        self.attributes("-transparentcolor", self.transparent_color)
elif sys.platform.startswith("darwin"):
        self.transparent_color = 'systemTransparent'
        self.attributes("-transparent", True)
else:
        self.transparent_color = '#000001' # not a transparent color
        corner_radius = 0 # make the frame corner radius=0

self.config(background=self.transparent_color)
...
```

- If we add these lines in the toplevel then it will not be shown as an extra window in taskbar:
```python
self.overrideredirect(True) 
self.resizable(width=True, height=True) 
self.transient(self.master) 
```
It works for mac, windows and linux also.

- Adding the options (values) inside the ctk scrollable frame so that the menu height can also be adjusted.

I don't think there will be any other issues... What do you think?

**Comment by Akascape** [comment]
@TomSchimansky
