### ISSUE TITLE
CTk geometry method

### ISSUE THREAD

**Issue by elentu12** [TomSchimansky/CustomTkinter#131]
Geometry method cant handle only positioning without changing size, for example:
`root.geometry('+100+100')`
Error:
`customtkinter\windows\ctk_tk.py", line 136, in geometry
    numbers = list(map(int, re.split(r"[x+]", geometry_string)))  # split geometry string into list of numbers
ValueError: invalid literal for int() with base 10: ''`

Also im unable to center a window with 150% scale using this formula:
`root.geometry(f"400x400+{int(1920/2 - root.winfo_width()/2)}+{int(1080/2 - root.winfo_height()/2)}")`
This works well with 100% scaling.
Thanks!

**Comment by TomSchimansky** [comment]
This should be fixed with the current version, I will try the center attempt though.

**Comment by elentu12** [comment]
I fixed the center formula by multiplying each side by 100/screen_scale. For example with 150% scale this should work:
`root.geometry(f"400x400+{int((1920/2 - root.winfo_width()/2) * 100/150)}+{int((1080/2 - root.winfo_height()/2) * 100/150)}")`
In conclussion, all positioning done by geometry method should be multiplied by 100/screen_scale to get the expected result

**Comment by KJo587** [comment]
I would like to be able to save the current geometry to a config file, but the CTk root.geomtry() does not return the current geometry as does a standard Tkinter root.geometry(). Should I start a new Issue, or, since this is also about geomrty, is it OK to ask about it here? 

If I try 
    print(root.geometry())

I get the following error:
   CTk.geometry() missing 1 required positional argument: 'geometry_string'

**Comment by TomSchimansky** [comment]
geometry method now returns the current geometry string with version 4.5.8.
