### ISSUE TITLE
customtkinter.CTkComboBox and a bind event for ComboboxSelected not working

### ISSUE THREAD

**Issue by Scr3wball88** [TomSchimansky/CustomTkinter#1371]
Hi, 

I have been using custom tkiinter now for a while and have grown to love it however i have found myself in a bit of a pickle with creating a bind event. Below firstly is the code i have: 

```
self.comboboxrole = customtkinter.CTkComboBox(master=self,
                                                      values=["Solutions User", "Incident Coordinator"],
                                                      width=250,
                                                      height=30)
self.comboboxrole.place(relx=0.5, rely=0.1, anchor=tkinter.CENTER)
self.comboboxrole.bind("<<ComboboxSelected>>", self.incidentcoordinator)
```
I am wanting to bind an event that when i click an option within the self.comboboxrole that it triggers a Method. The problem i have is the method is not calling as i believe the event used is from tkinter not customtkinter. Please see method below for the method code view:

```
def incidentcoordinator(self, event):
        print("IM RUNNING")
        if self.comboboxrole.get() == "Incident Coordinator":
            with open('C:\\TEMP\\emails.csv', newline='') as csvfile:
                reader = csv.reader(csvfile)
                email_list = [row[0] for row in reader]
            self.comboboxIC = customtkinter.CTkComboBox(master=self, values=email_list, width=250, height=30)
            self.comboboxIC.place(relx=0.5, rely=0.2, anchor=tkinter.CENTER)
            print(self.comboboxIC.winfo_geometry())
        else:
            if hasattr(self, 'comboboxIC'):
                self.comboboxIC.destroy()
```

To add i have also checked the event provided by customtkinter which states it is a button press but this event also does not trigger the bind as its used in other areas of the code. 

Does the combobox for customer tkinter support this kind of bind i am trying to achieve? 

Kind Regards
Austin

**Comment by Scr3wball88** [comment]
I did manage to get it to bind to <Button-1> however this does not work how its supposed to rather than you have to double click into the selected combobox entry. If there is anyway to use the <ComboBoxSelected> event that would be perfect.

**Comment by fufatujuba** [comment]
Hi @Scr3wball88, did you figured it out? Because I got same issue on the widget and shifted to using `command`  method that triggers by item selection event. 

`self.calibration_values = ['cal 1','cal 2','cal 3','...']
 self.calibration_string_var = tk.StringVar(value = self.calibration_values[0])
 self.cal_drop_down = ctk.CTkComboBox(master=self,font=ctk.CTkFont(family='Helvetica',size=12), variable =  self.calibration_string_var,values = self.calibration_values,command= lambda v: print(v))
  self.cal_drop_down.grid(row=0,column=2,sticky='NEWS')` 

output looks like the following.
![image](https://github.com/TomSchimansky/CustomTkinter/assets/16476437/2686c189-6fb0-406e-9223-a7d597ba297f)

**Comment by Scr3wball88** [comment]
Thanks for this, i actually gave up on this and used the method i mentioned above. 

Kind Regards
