### ISSUE TITLE
GUI performance

### ISSUE THREAD

**Issue by Cioscos** [TomSchimansky/CustomTkinter#1461]
Hi! I developed my first desktop application ever, and I choose to use customtkinter as library.
My project now is basically almost finished, I just want to add some other cool features.

But the thing that I really would like to improve are the performance. Indeed, both when I resize the window and when I scroll a scrollable widget I see some lag in the drawing of the widgets. I don't know what generates this problem and I think that my code to generate the gui is pretty good but because is my first code which uses a GUI, I want to know from you what could be the cause of my problems.

[Here you can find](https://github.com/Cioscos/easy-graphic-equalizer/releases/tag/v1.2.1) the release of my project that has been compiled with pyinstaller in order to be sharable.

The interested file is [this](https://github.com/Cioscos/easy-graphic-equalizer/blob/master/gui/main_window_gui.py).

Please let me know what I can change in the code to make the gui faster or if the problem is of the library in itself.

**Comment by TomSchimansky** [comment]
Tkinter itself is a very low performance ui-library, and drawing everything on a canvas for customtkinter does make it worse. So there is nothing I know of to improve the performance that is not already implemented. You can just make the window not resizable or use fewer widgets inside a scrollable frame for example. Otherwise you would have to use an other library, but there arent many options for python, I think pyqt is the only good perfomaning ui library for python similar to tkinter.
