### ISSUE TITLE
Frame bg_color not respected

### ISSUE THREAD

**Issue by Naatan** [TomSchimansky/CustomTkinter#155]
Take the following snippet:

```
import tkinter
from customtkinter import *

app = CTk()
CTkFrame(app, bg_color="red").pack(fill=tkinter.X, padx=10, pady=10)
app.mainloop()
```

When ran, you can see some slight red in the corners, but the frame is otherwise a dark grey:

![image](https://user-images.githubusercontent.com/278649/172029206-83f0e931-372a-4cee-9688-fd213b429e6c.png)

What's more, even when I don't specify a bg_color it still shows the dark grey background, even though customtkinter appears to set it to `None`, eg. https://github.com/TomSchimansky/CustomTkinter/blob/master/customtkinter/widgets/ctk_frame.py#L9

**Comment by TomSchimansky** [comment]
This behaviour is expected. The bg_color is indeed the color you see at the corners, behind the rounded frame. If you want to change the color of the frame, you have to set the fg_color attribute. This is different to normal tkinter, where there is only the bg attribute, and fg is often used for text color.
The grey color of the frame is also intended, the fg_color is set to a light gray for the first layer of frames directly on the window. And when you place a frame on a frame, it will get even darker, so that you can distinguish between them. This is also different to normal tkinter, where all frames are the same color as the window by default.
