### ISSUE TITLE
CTkFrame bug

### ISSUE THREAD

**Issue by EdwinRodger** [TomSchimansky/CustomTkinter#191]
Issue - When using ttk.Spinbox with CTkFrame, a bug happens where the frame curve doesn't get removed/added
Image - https://imgur.com/a/Ah60hJj
Source Code - https://sourceb.in/c5liD9C7Nk
Probable Cause - I have used grid() with label inside of frame by which it covered the curves of the frame
Probable solution - Either frame gives curves for both sides or it doesn't give curve at all
Edit : I only have this issue with above example, I don't know about other widgets

**Comment by TomSchimansky** [comment]
There is no bug, the label has a background color in CTk and it covered the edges of the frame. To prevent this you can decrease the dimensions of the label, so that it is only as big as it needs to be, to fit the text in it. And you can can set padding to the label and the Spinbox, so that there is some space between the frame edges and the widgets:
```python
from tkinter.ttk import Spinbox
import customtkinter as ctk

root = ctk.CTk()

date_frame = ctk.CTkFrame(root, fg_color="red", corner_radius=5)
date_frame.pack(pady=10)

lbl = ctk.CTkLabel(date_frame, text="Hello", height=10)
lbl.grid(row=0, column=0, padx=5, pady=5)

spinbox = Spinbox(date_frame)
spinbox.insert(1, "2022")
spinbox.grid(row=0, column=1, padx=5, pady=5)

root.mainloop()
```
<img width="641" alt="Bildschirmfoto 2022-06-15 um 21 46 12" src="https://user-images.githubusercontent.com/66446067/173913166-eab98bea-a3ee-4a94-a9bc-a9d5f5cb7144.png">

**Comment by TomSchimansky** [comment]
If you set fg_color="gray20" for the label you can see the space the label background covers:

<img width="685" alt="Bildschirmfoto 2022-06-15 um 21 47 57" src="https://user-images.githubusercontent.com/66446067/173913808-c40433d2-ddfd-4d5b-a90b-28675082e03c.png">
