### ISSUE TITLE
OptionMenu Border (border_width and _color)

### ISSUE THREAD

**Issue by Dotolox** [TomSchimansky/CustomTkinter#196]
![Screenshot_100](https://user-images.githubusercontent.com/60581626/174492348-973ad503-daf8-4894-9ed9-40eecb9dd3e1.png)

I'm using CTk on Windows 10 and 11. When Creating an OptionMenu I get this grey border around the dropdown section. When I define border_width=0 I get an error, that this parameter is not supported for OptionMenu. Same happens when I try to set border_color as the same color as the dropdown_color. Also the corners of the dropdown section are not round, like on the example picture on github.

**Comment by Dotolox** [comment]
I think it has noting to do with the default border of CTk, but why am I getting this border and a not round drop area?

**Comment by TomSchimansky** [comment]
Sadly it's not possible to remove this border on Windows. I changed the dropdown to a normal tkinter.Menu because of too many bugs with the custom one, and you cannot remove or color this border of the tkinter.Menu:

https://stackoverflow.com/questions/58678381/is-it-possible-to-change-the-menu-border-color-in-tkinter

**Comment by sumeshir26** [comment]
Instead of a ugly tkinter.Menu, why dont you use a ttk.Menu with a custom ttk style?

**Comment by TomSchimansky** [comment]
ttk has a menu? I only found a ttk.Menubutton...

**Comment by sumeshir26** [comment]
Its called a ttk.OptionMenu
