### ISSUE TITLE
How to clear a Scrollable Frame

### ISSUE THREAD

**Issue by joocam** [TomSchimansky/CustomTkinter#1965]
is there any way to remove everything inside a CTkScrollableFrame?

**Comment by DragonOfShuu** [comment]
First things first, I recommend creating a *discussion* instead of an *issue* because this isn't really an issue with the source code, and more like you need help with understanding the package.

To answer your question, you have a few options. In one of my projects, I added all child elements into a list where it could iterate through all objects and destroy each one. For example:
```python
def clear_content(self):
    while len(self.car_items) > 0:
        self.car_items[0].destroy()
        self.car_items.pop(0)
```

That one is a good option. However, after making a quick google search, I also found this:
```python
for child in infoFrame.winfo_children():
    child.destroy()
```

Let me know if this works for you!
