### ISSUE TITLE
[Feature Request] Support for SVG Icons

### ISSUE THREAD

**Issue by Heus-Sueh** [TomSchimansky/CustomTkinter#2109]
It would be interesting if CTkImage supported SVG to facilitate UI/GUI creation. Maybe do the automatic conversion from svg to png.

**Comment by Akascape** [comment]
@Heus-Sueh 
Ig you can do the conversion using PIL

**Comment by Akascape** [comment]
@Heus-Sueh There are many things in python libraries which you need to hack in order to get desired results. You can't just expect everything from the official side. 

If you are looking for svg icons, here is one library you may find helpful: 
https://github.com/israel-dryer/TkFontAwesome

This will also help you convert the svg data to icons.

**Comment by Heus-Sueh** [comment]
> @Heus-Sueh There are many things in python libraries which you need to hack in order to get desired results. You can't just expect everything from the official side. 
> 
> If you are looking for svg icons, here is one library you may find helpful: 
> https://github.com/israel-dryer/TkFontAwesome
> 
> This will also help you convert the svg data to icons.

I'm noticing this while I'm learning Python, and thanks for the suggestion, but this library is not installing in newer versions of Python because of some conflicts

**Comment by Pecako2001** [comment]
Okay cool, but as of interest why would you want to open an svg instead of an ico or others

**Comment by Akascape** [comment]
@Heus-Sueh Better convert them as it is a one time work only.
