### ISSUE TITLE
   from CustomTkinter import* ModuleNotFoundError: No module named 'CustomTkinter'

### ISSUE THREAD

**Issue by Samuel12209** [TomSchimansky/CustomTkinter#2224]
ive looked at all the other github issues and none of them seem to help, ive pip instaled this multiple times, swapped profiles and ive even run allmost any command on allmost every site ive found that has association to do with this, i am banging my head against the wall to try find a fix for this

**Comment by Samuel12209** [comment]
im also using pycharm

**Comment by Akascape** [comment]
@Samuel12209

The reason you are facing the error is because you have installed the package in a python version which you are not using, instead you are using a different version where it is not installed. 
Try swapping environment variables, see the versions.

Or start from scratch again, uninstaling everything.

**Comment by joocam** [comment]
bro, try 'customtkinter' instead 'CustomTkinter'...

**Comment by Samuel12209** [comment]
wasnt the customtkinter instead of CuestomTkinter it was a problem with directories
