### ISSUE TITLE
CTkButton's shape overridden by a default generated square shape

### ISSUE THREAD

**Issue by Mova801** [TomSchimansky/CustomTkinter#231]
# CTkButton's shape overridden by a default generated square shape
`python 3.10` `CTkButton` `corner_radius`

CTkButton's width and height does not fit corner radius well
---
### Root Code
```python
# root info
root = ct.CTk()
root.title = title  # CTk Title
root.geometry("900x600")
ct.set_appearance_mode("dark")
ct.set_default_color_theme("blue")
```
---
### CTkButton Code
```python
button_help = ct.CTkButton(
            master=root,
            image=info_img,
            command=info_button_event,
            text="",
            corner_radius=20,
            width=10,
            height=10
        )
        button_help.grid(row=0, column=2, padx=1, sticky="n")
```
---
### Expected result vs Result:
- ![expected_result](https://user-images.githubusercontent.com/60798187/177034246-cc9c62ba-aab9-4ea1-9f49-576d301a44d0.png) ![result](https://user-images.githubusercontent.com/60798187/177034247-850f9e85-96cc-491d-a9f2-f2cfa06aa2a9.PNG)

The right shape is drawn, but that square shouldn't be there.
- ![shape](https://user-images.githubusercontent.com/60798187/177034244-46429737-812c-41c4-9bb4-6e650dd71688.png)

---
Used image `128x128` `png`:
![info_img](https://user-images.githubusercontent.com/60798187/177033811-92ab5052-21d7-4a10-bbf7-b3f61c720721.png)

Function used to resize the image.
```python
def open_image(image_name: str, size: int) -> PIL.ImageTk.PhotoImage:
    """Opens and resizes an image file and returns it as PhotoImage."""
    image = PIL.Image.open(image_name).resize((size, size), PIL.Image.ANTIALIAS)
    return PIL.ImageTk.PhotoImage(image)

```
---

**Comment by TomSchimansky** [comment]
Sorry for the late response. I don't think this can be solved. The problem is, that in tkinter the background of a label cannot be transparent. And a CTkButton is just a canvas with a label on top and the image is placed in the label. So I need to set the background color of the label to the current background color of the button, so that you don't see the label. But the label has a rectangular shape, which covers the rounded corners, because its on top of the canvas, where the rounded corners a drawn. Maybe it would be possible if I place the label directly on the canvas, but I used a label because its much easier to create padding and position the label inside the CTkButton.

**Comment by TomSchimansky** [comment]
In your case a solution would be to crop the image, so that it fits the circle perfectly. Then you could make the button smaller and still get rounded corners.

**Comment by Akascape** [comment]
A new solution for this issue: https://github.com/TomSchimansky/CustomTkinter/discussions/2214
