### ISSUE TITLE
sticky option in .grid() not working

### ISSUE THREAD

**Issue by Nomanpour** [TomSchimansky/CustomTkinter#242]
Hello,

When using .grid() to put the widgets inside a frame sticky option doing nothing and all the widgets always stick to the left side.

**Comment by TomSchimansky** [comment]
You have to provide a minimal example of your code that's not working, otherwise it's not possible to detect what's going on.

**Comment by Nomanpour** [comment]
`
bottom_frame = ui.customtkinter.CTkFrame(master,
                                             width=master.winfo_width() - 10,
                                             height=40,
                                             fg_color=('#ebebec', '#212325')
                                             )
bottom_frame.grid_propagate(False) 
bottom_frame.grid(row=2, column=0, padx=5, pady=(0, 5), sticky='nsew')
`
`
_label = ui.customtkinter.CTkLabel(master=bottom_frame, text='Success', width=12)
_label.grid(row=0, column=3, padx=5, pady=5, sticky='e')
`
![image](https://user-images.githubusercontent.com/11517299/178207448-d641e5ee-c304-42c8-9381-a839be62dbca.png)

**Comment by TomSchimansky** [comment]
I think you have to set the weight of the grid cells you are using, otherwise the grid won't expand. So if you want to use a 1x4 grid in your bottom_frame, you have to set the weight like this: `botton_frame.grid_rowconfigure(1, weight=1)` and `bottom_frame.grid_columnconfigure((0, 1, 2, 3), weight=1)`. And then you can use the sticky option inside of the cell you placed the label into.

**Comment by Nomanpour** [comment]
You are right, my mistake.
Thank you.
