### ISSUE TITLE
CTKEntry font issue

### ISSUE THREAD

**Issue by salot18** [TomSchimansky/CustomTkinter#25]
![Untitled](https://user-images.githubusercontent.com/61282793/151590294-00992b9a-11fc-4b46-a62e-8c0e9fe49382.png)

It looks like we can't change the font property of an entry.

**Comment by ilify** [comment]
same here

**Comment by NiAmhras** [comment]
you can change it by simply use "font" instead of "text_font"

**Comment by ilify** [comment]
Acctually I fixed that(Added the arg) ,just replace the customtkinter_entry.py in the lib\site-packages\customtkinter by this one  https://github.com/ilify/fixed-customtkinter-lib

**Comment by TomSchimansky** [comment]
Thanks for mentioning this, I added the text_font argument to the CTkEntry now. Before you could only use it by using the normal font argument like NiAmhras said. I also pushed a new version to pip (2.1) where it's fixed (```pip3 install customtkinter --upgrade```)

In hindsight I should have not renamed the "font" argument to "text_font", that's totally unnecessary and creates confusion. Maybe I will change the next version so that both "font" and "text_font" are accepted and change the documentation to "font" as argument.
