### ISSUE TITLE
withdraw() doesn't work on main program at start.

### ISSUE THREAD

**Issue by MRFEZ1** [TomSchimansky/CustomTkinter#277]
When being used to hide the main window, the main window doesn't become hidden. Although, later when used through a function on a top level window, it disappears as it should.

**Comment by TomSchimansky** [comment]
Which platform are you using and which python version?

**Comment by MRFEZ1** [comment]
Using windows, python 3.7.9 and running it in Thonny

**Comment by ArielMAJ** [comment]
I just came here to start this same issue. I'm using Python 3.10 on Windows 11:


With tkinter, if you run this the window never pops up (as it should):
```
import tkinter as tk

root = tk.Tk()
root.withdraw()
root.mainloop()
```

With customtkinter, if you run this the window always pops up (it shouldn't):
```
import customtkinter

root = customtkinter.CTk()
root.withdraw()
root.mainloop()
```

Using `root.after(0,root.withdraw)` (instead of `root.withdraw()`) with tkinter also works pretty normally (the window doesn't even flash). With customtkinter it does hide the window but it flashes rapidly.


This customtkinter behavior leads to another problem that wouldn't happen if it did hide:
```
import customtkinter

root = customtkinter.CTk()
root.withdraw()
root.set_scaling(1, 1, 1)
root.geometry(f"{800}x{600}")
root.deiconify()
root.mainloop()
```
When resizing the window after calling set_scaling the user sees the window changing size (it should pop up already in the correct size, as tkinter normally does). I realized that calling set_scaling after geometry makes the window pop up in the correct size, but well...

I tried to look a bit into your implementation, but most of it is beyond the scope of my abilities and I can't really contribute much.

**Comment by ArielMAJ** [comment]
Doing some tests, I realized `root.geometry("+400+300")` works in tkinter but raises a ValueError in customtkinter.
```
…\customtkinter\windows\ctk_tk.py", line 136, in geometry
    numbers = list(map(int, re.split(r"[x+]", geometry_string)))  # split geometry string into list of numbers
ValueError: invalid literal for int() with base 10: ''
```

**Comment by felipetesc** [comment]
> 
Python 3.8
https://github.com/TomSchimansky/CustomTkinter/issues/101#issuecomment-1134194964

**Comment by TomSchimansky** [comment]
Should work now with version 4.5.11.
