### ISSUE TITLE
Bind event to CTkEntry 

### ISSUE THREAD

**Issue by NiAmhras** [TomSchimansky/CustomTkinter#28]
Is there a way to bind an event to the CTkEntry? The way shown in the code below isn't working: 

```python
import tkinter
import customtkinter

def Foo(self):
    print("Bar")

root_tk = customtkinter.CTk()


entry = customtkinter.CTkEntry(master=root_tk,
                               width=120,
                               height=25,
                               corner_radius=10)

entry.place(relx=0.5, rely=0.5, anchor=tkinter.CENTER)  
entry.bind('<Return>', Foo)

root_tk.mainloop()

**Comment by TomSchimansky** [comment]
The .bind() method does not work as you want at the moment, because it is called on the tkinter.Frame from which the CTkEntry is inherited. So to bind something to the CTkEntry you have to bind it to the .entry attribute:
```python
entry_1 = CTkEntry(...)
entry_1.entry.bind(...)
```
But in a future release I will change it so that the .bind() method on the CTkEntry will be automatically called on the .entry attribute, thanks for mentioning this.

**Comment by NiAmhras** [comment]
Thank you very much. Should have figured out it by myself.
