### ISSUE TITLE
Bug with getting the text of buttons

### ISSUE THREAD

**Issue by Hemang-Dwivedi** [TomSchimansky/CustomTkinter#36]
I am trying to get the text of a button and i am getting this error:

Traceback (most recent call last):
  File "xxxx\test.py", line 8, in <module>
    print(button['text'])
  File "D:\Python\lib\tkinter\__init__.py", line 1652, in cget
    return self.tk.call(self._w, 'cget', '-' + key)
_tkinter.TclError: unknown option "-text"

My code is 
from tkinter import *
import customtkinter
root = Tk()
frame = Frame(root)
button = customtkinter.CTkButton(frame, text="Tst")
button.grid(row=0,column=0)
frame.grid(row=3, column=1)
print(button['text'])
root.mainloop()

**Comment by TomSchimansky** [comment]
Access of attributes like this with brackets is not supported in CustomTkinter widgets. You could get the text by accessing the attribute directly: `print(button.text)`. But you shouldn't do it like this, because I can not guarantee you that the attribute will always be named `text`. 

Normally you shouldn't get into a situation, where you need to read the text from the button. Because if you read it from the button, this means you also set it to the button at some point. And the button should not be your storage, where you store the value. If you need the text of the button, simply store it in a variable.

You could also use a tkinter.StringVar() to set and access the text of the button. This is the best way. You pass the StringVar to the button, set the button text with the StringVar and get the text from the StringVar.
