### ISSUE TITLE
Problem converting python file to executable

### ISSUE THREAD

**Issue by fvictoor** [TomSchimansky/CustomTkinter#38]
Your code of exemples:

```
from tkinter import *
import tkinter
import customtkinter 

window_tl = customtkinter.CTk()
window_tl.geometry("800x400")
window_tl.title("Custom Tkinter")
customtkinter.set_appearance_mode("Dark")
customtkinter.set_default_color_theme("green")

nome = customtkinter.CTkLabel(master=window_tl,
                              text="Nome Completo:",
                              width=30,
                              height=25,
                              corner_radius=8)
nome.place(relx=0.2,
           rely=0.1,
           anchor=tkinter.E)



def botao():
    print("Botão apertado")

btn = customtkinter.CTkButton(master=window_tl,
                              text='Clique',
                              corner_radius=5, 
                              command=botao)

btn.place(relx=0.5,rely=0.5,anchor=tkinter.CENTER)

window_tl.mainloop()
```

Script to conversion:
pyinstaller --noconfirm --onefile --windowed  "......./CustomTkinter/TkinterCustom.py"

Error opening executable file:
![image](https://user-images.githubusercontent.com/76711024/159474946-96c05b42-e516-40ff-aee5-fbf409da9b1f.png)

**Comment by TomSchimansky** [comment]
I already know of this error, we discussed it here: https://github.com/TomSchimansky/CustomTkinter/issues/37
The problem is that the library not only includes .py files but also data files like .json, and so you cannot use the --onefile option with pyinstaller. And you have to add the customtkinter folder manually, because pyinstaller somehow does not include the data files in the library folder by default.

First you have to find the install location of the customtkinter library:
```pip show customtkinter```
For me this is: c:\users\<usern_ame>\appdata\local\programs\python\python310\lib\site-packages

Then you can add the customtkinter folder with the --add-data option of pyinstaller:
```
pyinstaller --noconfirm --onedir --windowed --add-data "C:/Users/<user_name>/AppData/Local/Programs/Python/Python310/Lib/site-packages/customtkinter;customtkinter/"  "C:/Users/<user_name>/Documents/CustomTkinter/examples/complex_example.py"
```

**Comment by fvictoor** [comment]
Thank you so much for your attention and explanation!!

**Comment by 1mkRE** [comment]
Hello after i creating my .exe file according to the description above respektively dokumentation, i get farther the error - Failed to execute script xxxx   in Windows 10 64 bit. First i tryed out to change my design at a bigger project with the same error, after that i tryed out any of your example project with the same problem.

Please is there any other solution to fix it?

Thanks.
