### ISSUE TITLE
AttributeError: module 'customtkinter' has no attribute 'CTK'

### ISSUE THREAD

**Issue by ahmadthegoat** [TomSchimansky/CustomTkinter#406]
I don't know what has happened, the program worked before but now this error keeps spawning. PLEASE HELP!

**Comment by TomSchimansky** [comment]
The window object is called `CTk` if you main that...

**Comment by rylemikoestrella** [comment]
![image](https://user-images.githubusercontent.com/13154564/185986121-a6cd753e-d606-4cc1-922e-2938756137d5.png)

No, we mean that this specific error 'module 'customtkinter' has no attribute 'CTk'' is happening, even on the README page's sample code. Other attributes no longer working are:
- set_default_color_blue
- Ctk()
- geometry
- mainloop() 
-  + many others

Would also like a guide to get through these because ctkinter was a fresh install from this device.
