### ISSUE TITLE
.CTkFrame width does not work

### ISSUE THREAD

**Issue by ruediger-reude** [TomSchimansky/CustomTkinter#48]
i downloaded your complex_example.py and changed the width parameter of the frames but nothing changes. Even when i delete the parameter, the frame width stays the same. The right frame only changes size if i change the whole window size (WIDTH variable in Class App).

Am i doing something wrong or is there something not working as intended?

**Comment by TomSchimansky** [comment]
Hi, in my `examples/complex_example.py`, the layout is done by using the tkinter grid geometry manager, not place or pack.  With the grid geometry manager, the size of a frame is mainly determined by the weight of the grid cell it is in and the size of the elements in the frame. You can't change the size with the `width` and `height` attributes. In my example the weight of the grid cell where the frame_left is in, isn't configured, so it is zero by default (`self.grid_columnconfigure(0, weight=0)`) which means the frame does not expand if there is space available. If you want to make the frame bigger, increase the x-padding of the buttons in the frame, so that they need more space. Then the minimum size of the frame_left will be bigger. And if you also want the frame to expand when there is space available (window resizing), then give the cell it is in a weight: `self.grid_columnconfigure(0, weight=1)`

The grid geometry manager can be confusing sometimes, but I would highly recommend using it, because you're window will be responsive when it gets resized, and it's very easy to change things afterwards when the whole layout is already built. If a button needs more space because of a longer text for example, you don't have to change anything of the layout, the button just gets the space it needs according to the weight of the cell it is in, and if the button is in a frame, the frame gets bigger automatically. So the other widgets relocate themselves automatically.
