### ISSUE TITLE
Adding a border to a button results in a clipped widget shape

### ISSUE THREAD

**Issue by avalon60** [TomSchimansky/CustomTkinter#498]
Adding a border to a CTkButton widget, results in the button shape being compromised. No border is evident, just a change in the button shape. This can be demonstrated, by taking the `simple_example.py` and changing the code, thus:

```
button_1 = customtkinter.CTkButton(master=frame_1, command=button_callback, borderwidth=3, border_color='red')
button_1.pack(pady=12, padx=10)
```
The result looks like this:

![image](https://user-images.githubusercontent.com/89534395/193450162-0237573e-d846-40da-b1f3-6336afa2083a.png)

**Comment by TomSchimansky** [comment]
You forgot the underscore inn the attribute name and wrote `borderwidth` instead of `border_width`. But that's a weak spot you found there. Because with the `borderwidth` attribute you configure the border with of the underlaying tkinter frame, which results in this strange behaviour. I will try to prevent this possibility.

**Comment by avalon60** [comment]
> You forgot the underscore inn the attribute name and wrote `borderwidth` instead of `border_width`. But that's a weak spot you found there. Because with the `borderwidth` attribute you configure the border with of the underlaying tkinter frame, which results in this strange behaviour. I will try to prevent this possibility.

Thanks Tom.
