### ISSUE TITLE
Button state functionality not working

### ISSUE THREAD

**Issue by Anurag-Nagpal** [TomSchimansky/CustomTkinter#5]
Hey!
I declared my button as 
`start_button = customtkinter.CTkButton(text="Start", fg_color=GREEN, command=start_timer)`

I tried to change the state of a button so that it would not work when clicked more than one time
`button.config(state=DISABLED)`
or
`button["state"] = "disabled"`

 and after the work(timer) is completed I reset it's state back to active 

`button["state"] = "active"`

**I am getting the following error**   
```
start_button.state(['disabled'])
AttributeError: 'CTkButton' object has no attribute 'state'
Exception in Tkinter callback
```
PS : This is the first time I am writing an issue.

**Comment by TomSchimansky** [comment]
Ok, you are getting the error because the CTkButton is actually just a modified Tkinter.Frame, and the Tkinter frame has no option for disabling it. And so at the moment you cannot disable the CTkButton, I never thought about this before. But if I have time, I will write a .disable() and .enable() function for the CTkButton in the next days, or I will overwrite the config() function.

**Comment by TomSchimansky** [comment]
I added button state functionality now.
You can do:
```python
button.configure(state=tkinter.DISABLED)
button.configure(state=tkinter.NORMAL)

current_state = button.state
```

**Comment by Anurag-Nagpal** [comment]
Awesome work! 
Thanks - error resolved
