### ISSUE TITLE
treeview

### ISSUE THREAD

**Issue by goyalharshit79** [TomSchimansky/CustomTkinter#50]
hey is there any way to use the customtkinter library with ttk widgets or more particularly treeview

**Comment by TomSchimansky** [comment]
Hey, no that's not possible, the CTk widgets have nothing to do with the actual tkinter or ttk widgets, they are all custom drawn with shapes on a canvas. So to create a treeview widget, I would have to create a new CTk widget and draw something like a treeview on the canvas. Maybe I will do this in the future, but not anytime soon, because there are more important problems and requests I am working on right now. Maybe you can try to build a treeview or list out of existing CTk widgets by yourself...

**Comment by goyalharshit79** [comment]
Hey, thanks for getting back to me, i made it work with a few twitches in
the colour scheme and made it look better.
Btw i love your custom library, it has made life so much easier.
