### ISSUE TITLE
rounding the button edges

### ISSUE THREAD

**Issue by tomh751** [TomSchimansky/CustomTkinter#51]
Hi, i created a button but every time i see it in my tkinter GUI, i get the border edges inside. is there any argument to remove the border and only keep the rounded button shape? exmaple for my problem in the picture
<img width="133" alt="button problem" src="https://user-images.githubusercontent.com/86208159/166223082-d3d877c0-cd47-44ae-8470-b8a85c810005.png">

**Comment by TomSchimansky** [comment]
Hi, do you want to remove the blue corner of the button shown in the image? That's not possible because of the way the button is created. The button is drawn on a tkinter.Canvas with canvas shapes and in tkinter it's not possible to make a canvas with transparent background. Therefore I set the bg color of the button canvas to the color of what's behind the button. So you have to place the button on something with a plain color.

**Comment by Akascape** [comment]
@tomh751 A new solution for this issue: https://github.com/TomSchimansky/CustomTkinter/discussions/2214
