### ISSUE TITLE
Is there a way to add a scrollbar within a CTKComboBox?

### ISSUE THREAD

**Issue by 32-git** [TomSchimansky/CustomTkinter#515]
As stated above, ideally I would like to have a scrollbar within my ComboBox instead of having it become longer and longer every time I add an option.

Is there a way to do this?

**Comment by Akascape** [comment]
@32-git I think the dropdown menu has some limitations. It is working on tkinter's menu widget and all the parameters for it are these: 

`['activebackground', 'activeborderwidth', 'activeforeground', 'background', 'bd', 'bg', 'borderwidth', 'cursor', 'disabledforeground', 'fg', 'font', 'foreground', 'postcommand', 'relief', 'selectcolor', 'takefocus', 'tearoff', 'tearoffcommand', 'title', 'type']`

There is no more customization available, so maybe we have to compromise with that only.

**Comment by TomSchimansky** [comment]
Yeah, tkinter has no scrollable dropdown menu so I can't do anything there. There is one with the ttk combobox I think, but you can't use it separated from the combobox.

**Comment by tripnip** [comment]
![image](https://github.com/TomSchimansky/CustomTkinter/assets/77412636/25aea879-1ae4-4a49-8930-221e8e417523)

Hi, related to the same thing, there is no scrollable for tkinter, but it has this option to click up and down to go through the list when it is big enough(which is only shown after the whole window is filled up with options), anybody has an idea to maybe atleast adjust the size(limit the maximum number of options showed), so that it does not look bad? Would be of great help :)

**Comment by Akascape** [comment]
@32-git 
@tripnip 
Use this dropdown menu: 
https://github.com/Akascape/CTkScrollableDropdown

You can adjust height, configure options, update values, scroll through option list etc.

**Comment by tripnip** [comment]
Thats a life saver, thanks :)
