### ISSUE TITLE
Issue with PyInstaller

### ISSUE THREAD

**Issue by kobbyboat** [TomSchimansky/CustomTkinter#54]
Has anyone resolved the problem with PyInstaller? What about you, Tom? How do we get around this issue?

**Comment by TomSchimansky** [comment]
Hi, did you look at wiki: https://github.com/TomSchimansky/CustomTkinter/wiki/Packaging
For me this method is working. The problem is that pyinstaller does not include data files like .json from libraries. I don't know if other libraries don't use data files, but I need to. So there isn't much I can do about this.

**Comment by heniu75** [comment]
I know this is closed but perhaps this will help someone - on OSX Monterey I ended up using pyinstaller to package using the following comment 'pyinstaller --noconfirm --onedir --add-data /usr/local/lib/python3.9/site-packages/customtkinter:customtkinter <name-of-script-file>.py'
