### ISSUE TITLE
Strange artefacts on CTkFrames when using high values for corner_radius

### ISSUE THREAD

**Issue by avalon60** [TomSchimansky/CustomTkinter#619]
I reproduced this problem on the complex_example.py.

Substituting this for the "create two frames" code and adding extra layers of frames:

```
        # ============ create two frames ============

        # configure grid layout (2x1)
        self.grid_columnconfigure(1, weight=1)
        self.grid_rowconfigure(0, weight=1)

        self.frame_left = customtkinter.CTkFrame(master=self,
                                                 width=180,
                                                 corner_radius=0)
        self.frame_left.grid(row=0, column=0, sticky="nswe")

        corner_radius = 100
        self.frame_mid = customtkinter.CTkFrame(master=self, corner_radius=corner_radius)
        self.frame_mid.grid(row=0, column=1, sticky="nswe", padx=20, pady=20)

        self.frame_high = customtkinter.CTkFrame(master=self.frame_mid, corner_radius=corner_radius)
        self.frame_high.grid(row=0, column=1, sticky="nswe", padx=20, pady=20)

        self.frame_right = customtkinter.CTkFrame(master=self.frame_high, corner_radius=corner_radius)
        self.frame_right.grid(row=0, column=1, sticky="nswe", padx=20, pady=20)
```

This results in the following effect (note the square edges):

![image](https://user-images.githubusercontent.com/89534395/201480450-579112db-c459-48de-bdc1-84a0b8ab512e.png)

**Comment by TomSchimansky** [comment]
This is expected a can not be solved. Since the tkinter.Canvas does not support transparency, the only way to get the effect of transparency is to get the foreground color of the parent widget and use it as a background color for the child widget. But of course the widgets and frames stay rectangular like this:

![201480450-579112db-c459-48de-bdc1-84a0b8ab512e](https://user-images.githubusercontent.com/66446067/201490165-05e52f6b-9db0-4321-9d9b-6f3330742093.png)

**Comment by avalon60** [comment]
Thanks Tom. I discovered this using the slider control for the geometry management in my theme builder app. Do you think it would be sensible for my app to set an upper limit, of say 75, or do you think the programmer should be allowed to push it this far?
