### ISSUE TITLE
New Update is not compatible with older applications

### ISSUE THREAD

**Issue by Akascape** [TomSchimansky/CustomTkinter#710]
@TomSchimansky 
The new update is not compatible with applications made in older versions. 
Many arguments for the widgets are replaced by new names.  Like **text_font** to **font**.
Please add the old arguments back, or maybe add both at the same time.

Moreover, the folder and theme structures are also changed :(

All the previous works are ruined.

**Comment by KaisoulTV** [comment]
You can just use vs or any text editor to replace all.

**Comment by TomSchimansky** [comment]
You can have a look at the changelog file to see which attribute names changed. I changed some attribute names so that they are more consistent with other widget attribute names. I renamed text_font to font because there were so much questions why the font attribute is not working and now its consistent with tkinter.

I will not add in the old attributes, because one of the most important things of designing a library is that the functions and attributes are named precisely and consistent and different names for the same functionality just cause confusion.

Lastly, I think the file structure of the library is much better now, I removed a ton of code duplicates and added a lot of base classes which hold the core functionality of the widgets and windows. Also I tried to adapt to the principal of using modules that hold functionality independent of other modules and are only dependant of sub-modules. All in all I think it's more readable now.
