### ISSUE TITLE
Request: CTkTextBox

### ISSUE THREAD

**Issue by jusspatel** [TomSchimansky/CustomTkinter#8]
Can a CustomTkinter TextBox be added too sometime in the future ?

**Comment by sumeshir26** [comment]
@jusspatel I think it alreaday exists

**Comment by TomSchimansky** [comment]
Currently there is only an EntryBox. To make a complete TextBox from scratch would be very difficult, because it needs scrolling and text-formatting. But I will see if I can embed a Tkinter TextBox into a frame with rounded corners.

**Comment by jusspatel** [comment]
do go ahead with this project though , because of all the modern themes for tkinter i have seen , this so far is the best and easiest to use :)

**Comment by felipetesc** [comment]
> Can a CustomTkinter TextBox be added too sometime in the future ?

Perhaps a password box too ?

**Comment by TomSchimansky** [comment]
A password entry can be done with normal Tkinter functionality and the CTkEntry also supports it. Have a look at this one if you not have already found it:
https://github.com/TomSchimansky/CustomTkinter/blob/master/examples/example_background_image.py

**Comment by devcameronj** [comment]
![image](https://user-images.githubusercontent.com/19158864/194717812-8facaa6d-b558-450e-afac-702ca771d9e4.png)

![image](https://user-images.githubusercontent.com/19158864/194718004-84d84a0b-03f2-44d4-9a0c-86433dd4f2f1.png)


Is it possible to add more functionality to the CTkTextBox such as a delete method? I have an app that's supposed to overwrite (not append) the textbox on each call, so I have to delete the current contents of the box. This works in vanilla Tkinter and I'd love to have this ability in CustomTkinter as well! If this already exists in the docs, please point me to it because I was unable to find it.

**Comment by TomSchimansky** [comment]
Textbox will be finished in the next days with version 5.0.0.

**Comment by rubensanchezrivero** [comment]
is there any news about textbox?

**Comment by Shuvadip-Ghosh** [comment]
> ![image](https://user-images.githubusercontent.com/19158864/194717812-8facaa6d-b558-450e-afac-702ca771d9e4.png)
> 
> ![image](https://user-images.githubusercontent.com/19158864/194718004-84d84a0b-03f2-44d4-9a0c-86433dd4f2f1.png)
> 
> Is it possible to add more functionality to the CTkTextBox such as a delete method? I have an app that's supposed to overwrite (not append) the textbox on each call, so I have to delete the current contents of the box. This works in vanilla Tkinter and I'd love to have this ability in CustomTkinter as well! If this already exists in the docs, please point me to it because I was unable to find it.

Sir can you please tell how to append I am loking for that..

**Comment by TomSchimansky** [comment]
I added the CTkTextbox now with version 5.0.0!

**Comment by Joshrocky** [comment]
@TomSchimansky  how do I add images on the CTkTextBox? Because it raises an error concerning embedding.
