### ISSUE TITLE
CustomTkinter shows all elements broken on WSLg

### ISSUE THREAD

**Issue by sblisesivdin** [TomSchimansky/CustomTkinter#86]
![CustomTkinter-on-WSLg](https://user-images.githubusercontent.com/10999129/168759673-2b7b518e-9bf9-42b0-bf97-7fddee7adae0.png)

All elements are corrupted. Dark mode/Light mode works fine.

**Comment by TomSchimansky** [comment]
Can you tell me what this prints for you on WSLg:
```python
import sys
import os
import platform

print(sys.platform)
print(os.name)
print(platform.system())
```

**Comment by sblisesivdin** [comment]
It gives:

    linux
    posix
    Linux

**Comment by TomSchimansky** [comment]
I don't know if I can do anything about it. In order to render the widgets with antialiasing, I use font shapes (circles) on the tkinter.Canvas, and therefore I need to load a custom font from a .otf file. On Linux I do this by copying the file into the `~/.fonts/` folder, then I can use it in customtkinter. But on WSLg this seems to be not working. But I didn't found some useful informaition on how to add custom fonts to the system on WLSg.

One thing you can do to get a usable interface is disabling the use of font shapes. Then normal tkinter canvas shapes will be used for rendering and the corners are not antialiased:
```python
import customtkinter

customtkinter.CTkSettings.preferred_drawing_method = "circle_shapes"  # 'polygon_shapes', 'font_shapes', 'circle_shapes'
```
(CTkSettings will be renamed to Settings in the next version)

Also I didn't found information on how to detect if python is running on WSLg, so I could disable the font shapes automatically.

**Comment by sblisesivdin** [comment]
Thank you for the detailed information. Using without aliasing works fine! Here is the final case:

![CustomTkinter-on-WSLg-solved](https://user-images.githubusercontent.com/10999129/169644978-57e05f7b-6738-4e2f-b566-321da0517069.png)

**Comment by TomSchimansky** [comment]
This
```python
customtkinter.CTkSettings.preferred_drawing_method = "circle_shapes"
```
has changed to this
```python
customtkinter.DrawEngine.preferred_drawing_method = "circle_shapes"
```
with version 4.0.0.
